routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::prefix('administration')->group(function () {
    /*
    |--------------------------------------------------------------------------
    | Permission Routes | Sentinel Implementation
    |--------------------------------------------------------------------------
    */
    Route::resource('permissions', 'Admin\PermissionsController');

    /*
    |--------------------------------------------------------------------------
    | Roles Routes | Sentinel Implementation
    |--------------------------------------------------------------------------
    */
    Route::resource('roles', 'Admin\RolesController');

    /*
    |--------------------------------------------------------------------------
    | Users Routes | Sentinel Implementation
    |--------------------------------------------------------------------------
    */
    Route::post('users/admin/store', ['as' => 'users.admin.store', 'uses' => 'Admin\UsersController@saveAdminUser']);
    Route::get('users/search/{idnum}', 'Admin\UsersController@searchClient');
    Route::resource('users', 'Admin\UsersController');

    /*
    |--------------------------------------------------------------------------
    | Login Routes | Sentinel Implementation
    |--------------------------------------------------------------------------
    */
    Route::get('login', ['as' => 'admin.login.page', 'uses' => 'Auth\LoginController@adminLoginPage']);
    Route::post('login', ['as' => 'login', 'uses' => 'Auth\LoginController@loginAttempt']);


    /*
    |--------------------------------------------------------------------------
    | Departments Routes
    |--------------------------------------------------------------------------
    */
    Route::resource('departments', 'Admin\DepartmentsController');

    /*
    |--------------------------------------------------------------------------
    | Cities Routes
    |--------------------------------------------------------------------------
    */
    Route::resource('departments/{department_id}/cities', 'Admin\CitiesController');

    /*
    |--------------------------------------------------------------------------
    | Admin Home Routes
    |--------------------------------------------------------------------------
    */
    Route::get('/', ['as' => 'admin.index', 'uses' => 'Admin\AdminHomeController@index']);

});

/*
|--------------------------------------------------------------------------
| Front Various Index
|--------------------------------------------------------------------------
*/
Route::get('about', ['as' => 'front.about', 'uses' => 'Front\HomeController@aboutUs']);
Route::get('contact', ['as' => 'front.contact.show', 'uses' => 'Front\HomeController@showContact']);
Route::get('/', ['as' => 'index', 'uses' => 'Front\HomeController@index']);
Route::get('lang/{lang}', ['as' => 'lang.switch', 'uses' => 'Front\HomeController@changeLanguage']);

app/Http/Controllers/Admin/CitiesController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\CategoriesRequest;
use App\Models\Cities;
use App\Models\Departments;
use App\Models\Categories;
use Intervention\Image\ImageManagerStatic as Image;

class CitiesController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }

    public function index($department_id)
    {
        if (!\Sentinel::getUser()->hasAccess('departments.add|edit')) {
            \Log::error('Unauthorized access attempt',
                ['user' => \Sentinel::getUser()->username, 'action' => \Request::route()->getActionName()]);
            return redirect('/')->with('error', 'No posee permisos para realizar esta accion.');
        }

        if ($department = Departments::find($department_id)) {
            $cities = Cities::where('department_id', $department_id)->paginate(20);

            return view('administration.cities.index', compact('cities', 'department'));
        } else {
            \Log::warning("CitiesController | Department {$department_id} not found");
            return redirect()->back()->with('error', 'Departamento no encontrado');
        }
    }


    public function create($department_id)
    {
        if (!\Sentinel::getUser()->hasAccess('departments.add|edit')) {
            \Log::error('Unauthorized access attempt',
                ['user' => \Sentinel::getUser()->username, 'action' => \Request::route()->getActionName()]);
            return redirect('/')->with('error', 'No posee permisos para realizar esta accion.');
        }

        \Log::info("CitiesController | Group to find: {$department_id}");
        if ($department = Departments::find($department_id)){
            return view('administration.cities.create', compact( 'department'));
        }
        return redirect()->back()->with('error', 'Departamento no encontrado');
    }

    public function store($department_id, CategoriesRequest $request)
    {
        if (!\Sentinel::getUser()->hasAccess('departments.add|edit')) {
            \Log::error('Unauthorized access attempt',
                ['user' => \Sentinel::getUser()->username, 'action' => \Request::route()->getActionName()]);
            return redirect('/')->with('error', 'No posee permisos para realizar esta accion.');
        }

        $input = $request->all();
        if ($department_id == 0 || is_null($department_id)){
            \Log::warning("CitiesController | City id cant be zero");
            return redirect()->back()->with('error', 'Debe asignar un departamento')->withInput();
        }

        $arrayToSave = ['description' => $input['description'], 'department_id' => $department_id];

        if (!$city = Cities::create($arrayToSave)){
            \Log::warning("CitiesController | Error while creating a new subCategory");
            return redirect()->back()->with('error', 'Error al intentar crear el registro')->withInput();
        }


        return redirect()->route('cities.index', $department_id)->with('success', 'Ciudad creada exitosamente');
    }

    public function edit($department_id, $id)
    {
        if (!\Sentinel::getUser()->hasAccess('departments.add|edit')) {
            \Log::error('Unauthorized access attempt',
                ['user' => \Sentinel::getUser()->username, 'action' => \Request::route()->getActionName()]);
            return redirect('/')->with('error', 'No posee permisos para realizar esta accion.');
        }

        if (!$department = Departments::find($department_id)){
            \Log::warning("CitiesController | Group {$id} not found");
            return redirect()->back()->with('error', 'Grupo no encontado');
        }


        if (!$city = Cities::find($id)){
            \Log::warning("CitiesController | Category {$id} not found");
            return redirect()->back()->with('error', 'SCategoria no encontada');
        }

        return view('administration.cities.edit', compact('city', 'department'));
    }

    public function update($department_id, CategoriesRequest $request, $id)
    {
        if (!\Sentinel::getUser()->hasAccess('departments.add|edit')) {
            \Log::error('Unauthorized access attempt',
                ['user' => \Sentinel::getUser()->username, 'action' => \Request::route()->getActionName()]);
            return redirect('/')->with('error', 'No posee permisos para realizar esta accion.');
        }

        if ($department_id == 0 || is_null($department_id)){
            \Log::warning("CitiesController | Group id cant be zero");
            return redirect()->back()->with('error', 'Debe asignar una categoria')->withInput();
        }

        if (!$department = Departments::find($department_id)){
            \Log::warning("CitiesController | Department {$id} not found");
            return redirect()->back()->with('error', 'Departamento no encontado');
        }


        if (!$city = Cities::find($id)){
            \Log::warning("CitiesController | City {$id} not found");
            return redirect()->back()->with('error', 'Ciudad no encontada');
        }

        $input = $request->all();

        if (!$city->update($input)){
            \Log::warning("CitiesController | Error trying to update city: {$id}");
            return redirect()->back()->with('error', 'Error al intentar actualizar el registro')->withInput();
        }


        return redirect()->route('cities.index', $department_id)->with('success', 'Ciudad actualizada exitosamente');
    }

    public function destroy($id, $subcategory_id)
    {
        $message = '';
        $error = '';

        \Log::info("Data: SubCategory: {$subcategory_id} | Category: {$id}");

        if (!\Sentinel::getUser()->hasAccess('categories.destroy')) {
            \Log::error('Unauthorized access attempt',
                ['user' => \Sentinel::getUser()->username, 'action' => \Request::route()->getActionName()]);
            $message = 'No posee permisos para realizar esta operacion';
            $error = true;
        } else {
            if ($role = Categories::find($subcategory_id)) {
                try {
                    if (Categories::destroy($subcategory_id)) {
                        $message = 'SubCategoria eliminada correctamente';
                        $error = false;
                    }
                } catch (\Exception $e) {
                    \Log::warning("CategoriesController | Error deleting SubCategory: " . $e->getMessage());
                    $message = 'Error al intentar eliminar la subcategoria';
                    $error = true;
                }
            } else {
                \Log::warning("CategoriesController | SubCategory {$subcategory_id} not found");
                $message = 'SubCategoria no encontrada';
                $error = true;
            }
        }


        return response()->json([
            'error' => $error,
            'message' => $message,
        ]);
    }

    private function uploadImage($input, $id)
    {
        if (array_key_exists('category_image', $input) && !is_null($input['category_image'])) {
            $fileName = $id . '.jpg';
            $image = $input['category_image'];
            $imageResize = Image::make($image->getRealPath());
//            $imageResize->resize(786, 378);
            $imageResize->save(public_path("admin/images/categories/{$fileName}"));
        }else{
            \Log::warning("CategoriesController | Image not found");
        }
    }





}

resources/views/administration/cities/create.blade.php
@extends('administration.templates.layout')
@section('content')
    <!-- #END# Vertical Layout -->
    <!-- Vertical Layout | With Floating Label -->
    <div class="row clearfix">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <div class="card">
                <div class="header">
                    <h2>
                        Nueva Ciudad para {{ $department->description }}
                        {{--<small>With floating label</small>--}}
                    </h2>
                </div>
                <div class="body">
                    {!! Form::open(['route' => ['cities.store', $department->id], 'method' => 'post', 'files' => 'true']) !!}
                    @include('administration.cities.partials.fields')
                    {{ Form::close() }}
                </div>
            </div>
        </div>
    </div>

    <!-- Vertical Layout | With Floating Label -->
@endsection

@section('css')
    <!-- Bootstrap Material Datetime Picker Css -->
    <link href="{{ '/admin/plugins/bootstrap-material-datetimepicker/css/bootstrap-material-datetimepicker.css' }}" rel="stylesheet" />

    <!-- Wait Me Css -->
    <link href="{{ '/admin/plugins/waitme/waitMe.css' }}" rel="stylesheet" />

    <!-- Bootstrap Select Css -->
    <link href="{{ '/admin/plugins/bootstrap-select/css/bootstrap-select.css' }}" rel="stylesheet" />
@endsection

@section('js')
    <!-- Moment Plugin Js -->
    <script src="{{ '/admin/plugins/momentjs/moment.js' }}"></script>
    <!-- Bootstrap Material Datetime Picker Plugin Js -->
    <script src="{{ '/admin/plugins/bootstrap-material-datetimepicker/js/bootstrap-material-datetimepicker.js' }}"></script>

    <script src="{{ '/admin/js/pages/forms/basic-form-elements.js' }}"></script>
@endsection

resources/views/administration/cities/edit.blade.php
@extends('administration.templates.layout')
@section('content')
    <!-- #END# Vertical Layout -->
    <!-- Vertical Layout | With Floating Label -->
    <div class="row clearfix">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <div class="card">
                <div class="header">
                    <h2>
                        Editar Ciudad
                        <small>{{ $department->description }} -> {{ $city->description }}</small>
                    </h2>
                </div>
                <div class="body">
                    {!! Form::model($city, ['route' => ['cities.update', $department->id, $city->id], 'method' => 'patch', 'files' => 'true']) !!}
                    @include('administration.cities.partials.fields')
                    {{ Form::close() }}
                </div>
            </div>
        </div>
    </div>
    <!-- Vertical Layout | With Floating Label -->
@endsection

resources/views/administration/cities/index.blade.php
@extends('administration.templates.layout')
@section('content')
    <div class="row clearfix">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <div class="card">
                <div class="header">
                    <h2>
                        Ciudades
                        <small>Seleccione una ciudad para continuar o agregue una nueva en el menu</small>
                    </h2>
                    <ul class="header-dropdown m-r--5">
                        <li class="dropdown">
                            <a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown" role="button"
                               aria-haspopup="true" aria-expanded="false">
                                <i class="material-icons">more_vert</i>
                            </a>
                            <ul class="dropdown-menu pull-right">
                                <li>
                                    <a href="{{ route('cities.create', ['department_id'=> $department->id]) }}">Nuevo</a>
                                </li>
                                <li><a href="{{ route('departments.index') }}">Ver todos los Departamentos</a></li>
                                {{--<li><a href="javascript:void(0);">Something else here</a></li>--}}
                            </ul>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <div class="row clearfix">
        @if($cities->isEmpty())
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <div class="card">
                    <div class="header">
                        <h2>
                            No existen ciudades asignadas para el departamento: {{ $department->description }}
                            <small>Agregue una nueva en el menu</small>
                        </h2>
                    </div>
                </div>
            </div>
        @else

            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <div class="card">
                    <div class="body table-responsive">
                        <table class="table">
                            <thead>
                            <tr>
                                <th>#</th>
                                <th>Descripción</th>
                                <th>Creado</th>
                                <th>Modificado</th>
                                <th>Acciones</th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($cities as $city)
                                <tr class="even pointer" data-id="{{ $city->id }}">
                                    <th scope="row">{{ $city->id }}</th>
                                    <td>{{ $city->description }}</td>
                                    <td>{{ $city->created_at }}</td>
                                    <td>{{ $city->updated_at }}</td>
                                    <td>
                                        <div class="icon-button-demo">
                                            <a href="{{ route('cities.edit', ['id' => $city->id, 'department_id'=> $department->id]) }}">
                                                <button class="btn btn-info waves-effect" type="button">
                                                    <i class="material-icons">border_color</i>
                                                </button>
                                            </a>
                                            <button class="btn btn-danger waves-effect btn-delete" type="button">
                                                <i class="material-icons">delete_forever</i>
                                            </button>
                                        </div>
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                        {{ $cities->links() }}
                    </div>
                </div>
            </div>
        @endif
    </div>

    {!! Form::open(['route' => ['categories.destroy', 'id' => ':ROW_ID', 'department_id' => $department->id], 'method' => 'DELETE',
                                  'id' => 'form-delete']) !!}
@endsection

@section('css')
    <!-- Sweetalert Css -->
    <link href="{{ '/admin/plugins/sweetalert/sweetalert.css' }}" rel="stylesheet"/>
@endsection
@section('js')
    <script src="{{ '/admin/plugins/sweetalert/sweetalert.min.js' }}"></script>
    @include('administration.templates.partials.delete_row')
@endsection